const interventions = [
    {
        id: '1',
        step: 'Open',
        status: 'Awaiting provider availability to start the job',
        problemType: 'Painting',
        apartmentId: '2',
        contractId: '',
        providerId: '5',
        quoteId: '1',
    },
    {
        id: '2',
        step: 'In Progress',
        status: 'Provider has started the plumbing work, in the initial stages',
        problemType: 'Plumbing',
        apartmentId: '1',
        contractId: '1',
        providerId: '2',
        quoteId: '2',
    },
    {
        id: '3',
        step: 'Closed Won',
        status: 'The electrical work has been completed successfully',
        problemType: 'Electricity',
        apartmentId: '3',
        contractId: '2',
        providerId: '1',
        quoteId: '3',
    },
    {
        id: '4',
        step: 'Closed Lost',
        status: 'Cleaning was cancelled due to client unavailability',
        problemType: 'Cleaning',
        apartmentId: '4',
        contractId: '',
        providerId: '4',
        quoteId: '4',
    },
    {
        id: '5',
        step: 'Blocked',
        status: 'Carpentry work blocked due to client delay in material delivery',
        problemType: 'Carpentry',
        apartmentId: '5',
        contractId: '3',
        providerId: '3',
        quoteId: '5',
    },
    {
        id: '6',
        step: 'In Progress',
        status: 'Plumbing job in progress, waiting on parts',
        problemType: 'Plumbing',
        apartmentId: '5',
        contractId: '3',
        providerId: '2',
        quoteId: '6',
    },
    {
        id: '7',
        step: 'Open',
        status: 'Waiting for the painting team to arrive',
        problemType: 'Painting',
        apartmentId: '7',
        contractId: '4',
        providerId: '5',
        quoteId: '7',
    },
    {
        id: '8',
        step: 'Closed Won',
        status: 'Electricity fixed, all systems running smoothly',
        problemType: 'Electricity',
        apartmentId: '10',
        contractId: '',
        providerId: '1',
        quoteId: '8',
    },
    {
        id: '9',
        step: 'In Progress',
        status: 'Carpentry work is ongoing for the furniture assembly',
        problemType: 'Carpentry',
        apartmentId: '11',
        contractId: '6',
        providerId: '3',
        quoteId: '9',
    },
    {
        id: '10',
        step: 'Closed Lost',
        status: 'Cleaning service was postponed due to weather conditions',
        problemType: 'Cleaning',
        apartmentId: '11',
        contractId: '6',
        providerId: '4',
        quoteId: '10',
    },
    {
        id: '11',
        step: 'Blocked',
        status: 'Electricity work delayed due to broken equipment',
        problemType: 'Electricity',
        apartmentId: '11',
        contractId: '6',
        providerId: '1',
        quoteId: '11',
    },
    {
        id: '12',
        step: 'In Progress',
        status: 'Painting has begun, first coat completed',
        problemType: 'Painting',
        apartmentId: '12',
        contractId: '',
        providerId: '5',
        quoteId: '12',
    },
    {
        id: '13',
        step: 'Closed Won',
        status: 'Plumbing problem resolved, no further issues reported',
        problemType: 'Plumbing',
        apartmentId: '12',
        contractId: '',
        providerId: '2',
        quoteId: '13',
    }
];

export default interventions;