const renters = [
    {
        id: '1',
        firstName: 'Alice',
        lastName: 'Green',
        email: 'alice.green@example.com',
        phone: '0507654321',
        tenantId: '1',
        apartmentId: '1',
        contractId: '1',
    },
    {
        id: '2',
        firstName: 'Bob',
        lastName: 'Brown',
        email: 'bob.brown@example.com',
        phone: '0521234567',
        tenantId: '1',
        apartmentId: '3',
        contractId: '2',
    },
    {
        id: '3',
        firstName: 'Catherine',
        lastName: 'Taylor',
        email: 'catherine.taylor@example.com',
        phone: '0538765432',
        tenantId: '1',
        apartmentId: '5',
        contractId: '3',
    },
    {
        id: '4',
        firstName: 'Daniel',
        lastName: 'Moore',
        email: 'daniel.moore@example.com',
        phone: '0549876543',
        tenantId: '1',
        apartmentId: '7',
        contractId: '4',
    },
    {
        id: '5',
        firstName: 'Evelyn',
        lastName: 'Walker',
        email: 'evelyn.walker@example.com',
        phone: '0552345678',
        tenantId: '1',
        apartmentId: '9',
        contractId: '5',
    },
    {
        id: '6',
        firstName: 'Frank',
        lastName: 'Young',
        email: 'frank.young@example.com',
        phone: '0563456789',
        tenantId: '1',
        apartmentId: '11',
        contractId: '6',
    },
    {
        id: '7',
        firstName: 'Grace',
        lastName: 'Harris',
        email: 'grace.harris@example.com',
        phone: '0574567890',
        tenantId: '1',
        apartmentId: '13',
        contractId: '7',
    }
];

export default renters;