const usersOfOrgData = [
    {
        id: 1,
        name: "Tech Solutions Inc.",
        users: 120,
        admins: 10,
        quotesSent: 250,
        proposalsSent: 80,
        moneyGenerated: 3500000,
    },
    {
        id: 2,
        name: "Global Innovations Group",
        users: 300,
        admins: 20,
        quotesSent: 400,
        proposalsSent: 120,
        moneyGenerated: 5000000,
    },
    {
        id: 3,
        name: "FutureTech Labs",
        users: 80,
        admins: 5,
        quotesSent: 150,
        proposalsSent: 50,
        moneyGenerated: 2000000,
    },
    {
        id: 4,
        name: "Smart Dynamics Ltd.",
        users: 90,
        admins: 8,
        quotesSent: 200,
        proposalsSent: 60,
        moneyGenerated: 2800000,
    },
    {
        id: 5,
        name: "NextGen Enterprises",
        users: 250,
        admins: 15,
        quotesSent: 320,
        proposalsSent: 110,
        moneyGenerated: 4200000,
    },
    {
        id: 6,
        name: "Blue Ocean Technologies",
        users: 75,
        admins: 6,
        quotesSent: 180,
        proposalsSent: 45,
        moneyGenerated: 2300000,
    },
    {
        id: 7,
        name: "Innovatech Systems",
        users: 130,
        admins: 12,
        quotesSent: 270,
        proposalsSent: 90,
        moneyGenerated: 3600000,
    },
    {
        id: 8,
        name: "Synergy Softworks",
        users: 110,
        admins: 10,
        quotesSent: 240,
        proposalsSent: 85,
        moneyGenerated: 3400000,
    },
    {
        id: 9,
        name: "AlphaCode Solutions",
        users: 60,
        admins: 4,
        quotesSent: 130,
        proposalsSent: 30,
        moneyGenerated: 1800000,
    },
    {
        id: 10,
        name: "Vanguard Tech",
        users: 95,
        admins: 9,
        quotesSent: 220,
        proposalsSent: 75,
        moneyGenerated: 3100000,
    },
    {
        id: 11,
        name: "Quantum Innovations",
        users: 185,
        admins: 14,
        quotesSent: 350,
        proposalsSent: 100,
        moneyGenerated: 4500000,
    },
    {
        id: 12,
        name: "Peak Performance Apps",
        users: 140,
        admins: 11,
        quotesSent: 300,
        proposalsSent: 90,
        moneyGenerated: 3800000,
    },
    {
        id: 13,
        name: "Skyline Systems",
        users: 70,
        admins: 7,
        quotesSent: 160,
        proposalsSent: 55,
        moneyGenerated: 2200000,
    },
    {
        id: 14,
        name: "Prism Digital Solutions",
        users: 160,
        admins: 13,
        quotesSent: 310,
        proposalsSent: 95,
        moneyGenerated: 3900000,
    },
    {
        id: 15,
        name: "Elemental IT Services",
        users: 100,
        admins: 9,
        quotesSent: 230,
        proposalsSent: 70,
        moneyGenerated: 3200000,
    },
    {
        id: 16,
        name: "CoreLogic Consulting",
        users: 200,
        admins: 16,
        quotesSent: 370,
        proposalsSent: 105,
        moneyGenerated: 4600000,
    },
    {
        id: 17,
        name: "Digital Horizon Labs",
        users: 85,
        admins: 7,
        quotesSent: 190,
        proposalsSent: 65,
        moneyGenerated: 2600000,
    },
    {
        id: 18,
        name: "Visionary Tech Corp",
        users: 125,
        admins: 11,
        quotesSent: 280,
        proposalsSent: 85,
        moneyGenerated: 3500000,
    },
    {
        id: 19,
        name: "Matrix Solutions",
        users: 230,
        admins: 18,
        quotesSent: 400,
        proposalsSent: 120,
        moneyGenerated: 4700000,
    },
    {
        id: 20,
        name: "BrightMind Technologies",
        users: 65,
        admins: 5,
        quotesSent: 140,
        proposalsSent: 40,
        moneyGenerated: 1900000,
    },
    {
        id: 21,
        name: "NeoTech Global",
        users: 175,
        admins: 14,
        quotesSent: 340,
        proposalsSent: 100,
        moneyGenerated: 4300000,
    },
    {
        id: 22,
        name: "DataFlow Enterprises",
        users: 210,
        admins: 17,
        quotesSent: 380,
        proposalsSent: 115,
        moneyGenerated: 4800000,
    },
    {
        id: 23,
        name: "Pioneer Apps Group",
        users: 150,
        admins: 12,
        quotesSent: 290,
        proposalsSent: 90,
        moneyGenerated: 3700000,
    },
    {
        id: 24,
        name: "Infinite Solutions",
        users: 90,
        admins: 7,
        quotesSent: 210,
        proposalsSent: 65,
        moneyGenerated: 3000000,
    },
    {
        id: 25,
        name: "Vertex Innovations",
        users: 220,
        admins: 18,
        quotesSent: 360,
        proposalsSent: 110,
        moneyGenerated: 4400000,
    },
    {
        id: 26,
        name: "NexaTech Systems",
        users: 80,
        admins: 6,
        quotesSent: 170,
        proposalsSent: 50,
        moneyGenerated: 2400000,
    },
    {
        id: 27,
        name: "Impact Digital Services",
        users: 130,
        admins: 10,
        quotesSent: 260,
        proposalsSent: 80,
        moneyGenerated: 3400000,
    },
    {
        id: 28,
        name: "Hyperion Technologies",
        users: 100,
        admins: 8,
        quotesSent: 230,
        proposalsSent: 70,
        moneyGenerated: 3100000,
    },
    {
        id: 29,
        name: "TechStream Solutions",
        users: 155,
        admins: 13,
        quotesSent: 300,
        proposalsSent: 95,
        moneyGenerated: 3800000,
    },
    {
        id: 30,
        name: "Frontier Digital Labs",
        users: 140,
        admins: 10,
        quotesSent: 310,
        proposalsSent: 85,
        moneyGenerated: 3600000,
    },
];

export default usersOfOrgData;